# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Offat < Formula
  desc "Autonomous REST API Vulnerability Assessment Tool"
  homepage "https://owasp.org/OFFAT/"
  version "0.21.0-beta"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/owasp-offat/offat/releases/download/v0.21.0-beta/offat_Darwin_amd64.zip"
      sha256 "8b7310447a0a6856b7ea519361d425870b52dcf011381827a9890b36bd0c69fe"

      def install
        bin.install "offat"
      end
    end
    on_arm do
      url "https://github.com/owasp-offat/offat/releases/download/v0.21.0-beta/offat_Darwin_arm64.zip"
      sha256 "1146b7993d106f863ae1c5f9c6a2bec93f21dd9fd0ff9e5e4812bf9bc42ffdbf"

      def install
        bin.install "offat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/owasp-offat/offat/releases/download/v0.21.0-beta/offat_Linux_amd64.zip"
        sha256 "9067e585976021a577f566aff40d2109a89ec2057d71994f5ab12a6e8f99908f"

        def install
          bin.install "offat"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/owasp-offat/offat/releases/download/v0.21.0-beta/offat_Linux_arm.zip"
        sha256 "cfc902a1fb9d33b8fa166a9570467228d15c3f4d0e804a34731d80c2a59bdbc3"

        def install
          bin.install "offat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/owasp-offat/offat/releases/download/v0.21.0-beta/offat_Linux_arm64.zip"
        sha256 "d0eff557b571f87771df8abb804b5d26de015339f0b84fcf29c42ccd41270935"

        def install
          bin.install "offat"
        end
      end
    end
  end

  test do
    system "#{bin}/offat -v"
  end
end
